// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "52c98d0fecf7810f632b411d205aa10f0f2f4d02c1a34b16906e4adb9f3f82cb")
