// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "ae12e6d73c400c6c5572cfc06fc78b23c04a2b90263b0ac8ee125178dc345355")
