// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/security/api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetEventParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventParams) Reset()         { *m = GetEventParams{} }
func (m *GetEventParams) String() string { return proto.CompactTextString(m) }
func (*GetEventParams) ProtoMessage()    {}
func (*GetEventParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{0}
}

func (m *GetEventParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventParams.Unmarshal(m, b)
}
func (m *GetEventParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventParams.Marshal(b, m, deterministic)
}
func (m *GetEventParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventParams.Merge(m, src)
}
func (m *GetEventParams) XXX_Size() int {
	return xxx_messageInfo_GetEventParams.Size(m)
}
func (m *GetEventParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventParams proto.InternalMessageInfo

type SecurityEventMessage struct {
	RuleID               string   `protobuf:"bytes,1,opt,name=RuleID,proto3" json:"RuleID,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Service              string   `protobuf:"bytes,4,opt,name=Service,proto3" json:"Service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityEventMessage) Reset()         { *m = SecurityEventMessage{} }
func (m *SecurityEventMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityEventMessage) ProtoMessage()    {}
func (*SecurityEventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{1}
}

func (m *SecurityEventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityEventMessage.Unmarshal(m, b)
}
func (m *SecurityEventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityEventMessage.Marshal(b, m, deterministic)
}
func (m *SecurityEventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityEventMessage.Merge(m, src)
}
func (m *SecurityEventMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityEventMessage.Size(m)
}
func (m *SecurityEventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityEventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityEventMessage proto.InternalMessageInfo

func (m *SecurityEventMessage) GetRuleID() string {
	if m != nil {
		return m.RuleID
	}
	return ""
}

func (m *SecurityEventMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SecurityEventMessage) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SecurityEventMessage) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type DumpProcessCacheParams struct {
	WithArgs             bool     `protobuf:"varint,1,opt,name=WithArgs,proto3" json:"WithArgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpProcessCacheParams) Reset()         { *m = DumpProcessCacheParams{} }
func (m *DumpProcessCacheParams) String() string { return proto.CompactTextString(m) }
func (*DumpProcessCacheParams) ProtoMessage()    {}
func (*DumpProcessCacheParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{2}
}

func (m *DumpProcessCacheParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpProcessCacheParams.Unmarshal(m, b)
}
func (m *DumpProcessCacheParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpProcessCacheParams.Marshal(b, m, deterministic)
}
func (m *DumpProcessCacheParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpProcessCacheParams.Merge(m, src)
}
func (m *DumpProcessCacheParams) XXX_Size() int {
	return xxx_messageInfo_DumpProcessCacheParams.Size(m)
}
func (m *DumpProcessCacheParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpProcessCacheParams.DiscardUnknown(m)
}

var xxx_messageInfo_DumpProcessCacheParams proto.InternalMessageInfo

func (m *DumpProcessCacheParams) GetWithArgs() bool {
	if m != nil {
		return m.WithArgs
	}
	return false
}

type SecurityDumpProcessCacheMessage struct {
	Filename             string   `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityDumpProcessCacheMessage) Reset()         { *m = SecurityDumpProcessCacheMessage{} }
func (m *SecurityDumpProcessCacheMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityDumpProcessCacheMessage) ProtoMessage()    {}
func (*SecurityDumpProcessCacheMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{3}
}

func (m *SecurityDumpProcessCacheMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityDumpProcessCacheMessage.Unmarshal(m, b)
}
func (m *SecurityDumpProcessCacheMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityDumpProcessCacheMessage.Marshal(b, m, deterministic)
}
func (m *SecurityDumpProcessCacheMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityDumpProcessCacheMessage.Merge(m, src)
}
func (m *SecurityDumpProcessCacheMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityDumpProcessCacheMessage.Size(m)
}
func (m *SecurityDumpProcessCacheMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityDumpProcessCacheMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityDumpProcessCacheMessage proto.InternalMessageInfo

func (m *SecurityDumpProcessCacheMessage) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type DumpNetworkNamespaceParams struct {
	SnapshotInterfaces   bool     `protobuf:"varint,1,opt,name=SnapshotInterfaces,proto3" json:"SnapshotInterfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpNetworkNamespaceParams) Reset()         { *m = DumpNetworkNamespaceParams{} }
func (m *DumpNetworkNamespaceParams) String() string { return proto.CompactTextString(m) }
func (*DumpNetworkNamespaceParams) ProtoMessage()    {}
func (*DumpNetworkNamespaceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{4}
}

func (m *DumpNetworkNamespaceParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpNetworkNamespaceParams.Unmarshal(m, b)
}
func (m *DumpNetworkNamespaceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpNetworkNamespaceParams.Marshal(b, m, deterministic)
}
func (m *DumpNetworkNamespaceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpNetworkNamespaceParams.Merge(m, src)
}
func (m *DumpNetworkNamespaceParams) XXX_Size() int {
	return xxx_messageInfo_DumpNetworkNamespaceParams.Size(m)
}
func (m *DumpNetworkNamespaceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpNetworkNamespaceParams.DiscardUnknown(m)
}

var xxx_messageInfo_DumpNetworkNamespaceParams proto.InternalMessageInfo

func (m *DumpNetworkNamespaceParams) GetSnapshotInterfaces() bool {
	if m != nil {
		return m.SnapshotInterfaces
	}
	return false
}

type DumpNetworkNamespaceMessage struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	DumpFilename         string   `protobuf:"bytes,2,opt,name=DumpFilename,proto3" json:"DumpFilename,omitempty"`
	GraphFilename        string   `protobuf:"bytes,3,opt,name=GraphFilename,proto3" json:"GraphFilename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpNetworkNamespaceMessage) Reset()         { *m = DumpNetworkNamespaceMessage{} }
func (m *DumpNetworkNamespaceMessage) String() string { return proto.CompactTextString(m) }
func (*DumpNetworkNamespaceMessage) ProtoMessage()    {}
func (*DumpNetworkNamespaceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{5}
}

func (m *DumpNetworkNamespaceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpNetworkNamespaceMessage.Unmarshal(m, b)
}
func (m *DumpNetworkNamespaceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpNetworkNamespaceMessage.Marshal(b, m, deterministic)
}
func (m *DumpNetworkNamespaceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpNetworkNamespaceMessage.Merge(m, src)
}
func (m *DumpNetworkNamespaceMessage) XXX_Size() int {
	return xxx_messageInfo_DumpNetworkNamespaceMessage.Size(m)
}
func (m *DumpNetworkNamespaceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpNetworkNamespaceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DumpNetworkNamespaceMessage proto.InternalMessageInfo

func (m *DumpNetworkNamespaceMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DumpNetworkNamespaceMessage) GetDumpFilename() string {
	if m != nil {
		return m.DumpFilename
	}
	return ""
}

func (m *DumpNetworkNamespaceMessage) GetGraphFilename() string {
	if m != nil {
		return m.GraphFilename
	}
	return ""
}

type GetConfigParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigParams) Reset()         { *m = GetConfigParams{} }
func (m *GetConfigParams) String() string { return proto.CompactTextString(m) }
func (*GetConfigParams) ProtoMessage()    {}
func (*GetConfigParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{6}
}

func (m *GetConfigParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigParams.Unmarshal(m, b)
}
func (m *GetConfigParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigParams.Marshal(b, m, deterministic)
}
func (m *GetConfigParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigParams.Merge(m, src)
}
func (m *GetConfigParams) XXX_Size() int {
	return xxx_messageInfo_GetConfigParams.Size(m)
}
func (m *GetConfigParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigParams proto.InternalMessageInfo

type SecurityConfigMessage struct {
	RuntimeEnabled       bool     `protobuf:"varint,1,opt,name=RuntimeEnabled,proto3" json:"RuntimeEnabled,omitempty"`
	FIMEnabled           bool     `protobuf:"varint,2,opt,name=FIMEnabled,proto3" json:"FIMEnabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityConfigMessage) Reset()         { *m = SecurityConfigMessage{} }
func (m *SecurityConfigMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityConfigMessage) ProtoMessage()    {}
func (*SecurityConfigMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{7}
}

func (m *SecurityConfigMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityConfigMessage.Unmarshal(m, b)
}
func (m *SecurityConfigMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityConfigMessage.Marshal(b, m, deterministic)
}
func (m *SecurityConfigMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityConfigMessage.Merge(m, src)
}
func (m *SecurityConfigMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityConfigMessage.Size(m)
}
func (m *SecurityConfigMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityConfigMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityConfigMessage proto.InternalMessageInfo

func (m *SecurityConfigMessage) GetRuntimeEnabled() bool {
	if m != nil {
		return m.RuntimeEnabled
	}
	return false
}

func (m *SecurityConfigMessage) GetFIMEnabled() bool {
	if m != nil {
		return m.FIMEnabled
	}
	return false
}

type RunSelfTestParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunSelfTestParams) Reset()         { *m = RunSelfTestParams{} }
func (m *RunSelfTestParams) String() string { return proto.CompactTextString(m) }
func (*RunSelfTestParams) ProtoMessage()    {}
func (*RunSelfTestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{8}
}

func (m *RunSelfTestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunSelfTestParams.Unmarshal(m, b)
}
func (m *RunSelfTestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunSelfTestParams.Marshal(b, m, deterministic)
}
func (m *RunSelfTestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunSelfTestParams.Merge(m, src)
}
func (m *RunSelfTestParams) XXX_Size() int {
	return xxx_messageInfo_RunSelfTestParams.Size(m)
}
func (m *RunSelfTestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RunSelfTestParams.DiscardUnknown(m)
}

var xxx_messageInfo_RunSelfTestParams proto.InternalMessageInfo

type ReloadPoliciesParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadPoliciesParams) Reset()         { *m = ReloadPoliciesParams{} }
func (m *ReloadPoliciesParams) String() string { return proto.CompactTextString(m) }
func (*ReloadPoliciesParams) ProtoMessage()    {}
func (*ReloadPoliciesParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{9}
}

func (m *ReloadPoliciesParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadPoliciesParams.Unmarshal(m, b)
}
func (m *ReloadPoliciesParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadPoliciesParams.Marshal(b, m, deterministic)
}
func (m *ReloadPoliciesParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadPoliciesParams.Merge(m, src)
}
func (m *ReloadPoliciesParams) XXX_Size() int {
	return xxx_messageInfo_ReloadPoliciesParams.Size(m)
}
func (m *ReloadPoliciesParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadPoliciesParams.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadPoliciesParams proto.InternalMessageInfo

type ReloadPoliciesResultMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadPoliciesResultMessage) Reset()         { *m = ReloadPoliciesResultMessage{} }
func (m *ReloadPoliciesResultMessage) String() string { return proto.CompactTextString(m) }
func (*ReloadPoliciesResultMessage) ProtoMessage()    {}
func (*ReloadPoliciesResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{10}
}

func (m *ReloadPoliciesResultMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadPoliciesResultMessage.Unmarshal(m, b)
}
func (m *ReloadPoliciesResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadPoliciesResultMessage.Marshal(b, m, deterministic)
}
func (m *ReloadPoliciesResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadPoliciesResultMessage.Merge(m, src)
}
func (m *ReloadPoliciesResultMessage) XXX_Size() int {
	return xxx_messageInfo_ReloadPoliciesResultMessage.Size(m)
}
func (m *ReloadPoliciesResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadPoliciesResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadPoliciesResultMessage proto.InternalMessageInfo

type SecuritySelfTestResultMessage struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecuritySelfTestResultMessage) Reset()         { *m = SecuritySelfTestResultMessage{} }
func (m *SecuritySelfTestResultMessage) String() string { return proto.CompactTextString(m) }
func (*SecuritySelfTestResultMessage) ProtoMessage()    {}
func (*SecuritySelfTestResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{11}
}

func (m *SecuritySelfTestResultMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecuritySelfTestResultMessage.Unmarshal(m, b)
}
func (m *SecuritySelfTestResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecuritySelfTestResultMessage.Marshal(b, m, deterministic)
}
func (m *SecuritySelfTestResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecuritySelfTestResultMessage.Merge(m, src)
}
func (m *SecuritySelfTestResultMessage) XXX_Size() int {
	return xxx_messageInfo_SecuritySelfTestResultMessage.Size(m)
}
func (m *SecuritySelfTestResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecuritySelfTestResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecuritySelfTestResultMessage proto.InternalMessageInfo

func (m *SecuritySelfTestResultMessage) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *SecuritySelfTestResultMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetStatusParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusParams) Reset()         { *m = GetStatusParams{} }
func (m *GetStatusParams) String() string { return proto.CompactTextString(m) }
func (*GetStatusParams) ProtoMessage()    {}
func (*GetStatusParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{12}
}

func (m *GetStatusParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusParams.Unmarshal(m, b)
}
func (m *GetStatusParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusParams.Marshal(b, m, deterministic)
}
func (m *GetStatusParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusParams.Merge(m, src)
}
func (m *GetStatusParams) XXX_Size() int {
	return xxx_messageInfo_GetStatusParams.Size(m)
}
func (m *GetStatusParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusParams proto.InternalMessageInfo

type ConstantValueAndSource struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Value                uint64   `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=Source,proto3" json:"Source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConstantValueAndSource) Reset()         { *m = ConstantValueAndSource{} }
func (m *ConstantValueAndSource) String() string { return proto.CompactTextString(m) }
func (*ConstantValueAndSource) ProtoMessage()    {}
func (*ConstantValueAndSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{13}
}

func (m *ConstantValueAndSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstantValueAndSource.Unmarshal(m, b)
}
func (m *ConstantValueAndSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstantValueAndSource.Marshal(b, m, deterministic)
}
func (m *ConstantValueAndSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstantValueAndSource.Merge(m, src)
}
func (m *ConstantValueAndSource) XXX_Size() int {
	return xxx_messageInfo_ConstantValueAndSource.Size(m)
}
func (m *ConstantValueAndSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstantValueAndSource.DiscardUnknown(m)
}

var xxx_messageInfo_ConstantValueAndSource proto.InternalMessageInfo

func (m *ConstantValueAndSource) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ConstantValueAndSource) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *ConstantValueAndSource) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type SelfTestsStatus struct {
	LastTimestamp        string   `protobuf:"bytes,1,opt,name=LastTimestamp,proto3" json:"LastTimestamp,omitempty"`
	Success              []string `protobuf:"bytes,2,rep,name=Success,proto3" json:"Success,omitempty"`
	Fails                []string `protobuf:"bytes,3,rep,name=Fails,proto3" json:"Fails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfTestsStatus) Reset()         { *m = SelfTestsStatus{} }
func (m *SelfTestsStatus) String() string { return proto.CompactTextString(m) }
func (*SelfTestsStatus) ProtoMessage()    {}
func (*SelfTestsStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{14}
}

func (m *SelfTestsStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfTestsStatus.Unmarshal(m, b)
}
func (m *SelfTestsStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfTestsStatus.Marshal(b, m, deterministic)
}
func (m *SelfTestsStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfTestsStatus.Merge(m, src)
}
func (m *SelfTestsStatus) XXX_Size() int {
	return xxx_messageInfo_SelfTestsStatus.Size(m)
}
func (m *SelfTestsStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfTestsStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SelfTestsStatus proto.InternalMessageInfo

func (m *SelfTestsStatus) GetLastTimestamp() string {
	if m != nil {
		return m.LastTimestamp
	}
	return ""
}

func (m *SelfTestsStatus) GetSuccess() []string {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *SelfTestsStatus) GetFails() []string {
	if m != nil {
		return m.Fails
	}
	return nil
}

type Status struct {
	Environment          *EnvironmentStatus `protobuf:"bytes,1,opt,name=Environment,proto3" json:"Environment,omitempty"`
	SelfTests            *SelfTestsStatus   `protobuf:"bytes,2,opt,name=SelfTests,proto3" json:"SelfTests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{15}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetEnvironment() *EnvironmentStatus {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *Status) GetSelfTests() *SelfTestsStatus {
	if m != nil {
		return m.SelfTests
	}
	return nil
}

type ConstantFetcherStatus struct {
	Fetchers             []string                  `protobuf:"bytes,1,rep,name=Fetchers,proto3" json:"Fetchers,omitempty"`
	Values               []*ConstantValueAndSource `protobuf:"bytes,2,rep,name=Values,proto3" json:"Values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ConstantFetcherStatus) Reset()         { *m = ConstantFetcherStatus{} }
func (m *ConstantFetcherStatus) String() string { return proto.CompactTextString(m) }
func (*ConstantFetcherStatus) ProtoMessage()    {}
func (*ConstantFetcherStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{16}
}

func (m *ConstantFetcherStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstantFetcherStatus.Unmarshal(m, b)
}
func (m *ConstantFetcherStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstantFetcherStatus.Marshal(b, m, deterministic)
}
func (m *ConstantFetcherStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstantFetcherStatus.Merge(m, src)
}
func (m *ConstantFetcherStatus) XXX_Size() int {
	return xxx_messageInfo_ConstantFetcherStatus.Size(m)
}
func (m *ConstantFetcherStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstantFetcherStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ConstantFetcherStatus proto.InternalMessageInfo

func (m *ConstantFetcherStatus) GetFetchers() []string {
	if m != nil {
		return m.Fetchers
	}
	return nil
}

func (m *ConstantFetcherStatus) GetValues() []*ConstantValueAndSource {
	if m != nil {
		return m.Values
	}
	return nil
}

type EnvironmentStatus struct {
	Warnings             []string               `protobuf:"bytes,1,rep,name=Warnings,proto3" json:"Warnings,omitempty"`
	Constants            *ConstantFetcherStatus `protobuf:"bytes,2,opt,name=Constants,proto3" json:"Constants,omitempty"`
	KernelLockdown       string                 `protobuf:"bytes,3,opt,name=KernelLockdown,proto3" json:"KernelLockdown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EnvironmentStatus) Reset()         { *m = EnvironmentStatus{} }
func (m *EnvironmentStatus) String() string { return proto.CompactTextString(m) }
func (*EnvironmentStatus) ProtoMessage()    {}
func (*EnvironmentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{17}
}

func (m *EnvironmentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentStatus.Unmarshal(m, b)
}
func (m *EnvironmentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentStatus.Marshal(b, m, deterministic)
}
func (m *EnvironmentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentStatus.Merge(m, src)
}
func (m *EnvironmentStatus) XXX_Size() int {
	return xxx_messageInfo_EnvironmentStatus.Size(m)
}
func (m *EnvironmentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentStatus proto.InternalMessageInfo

func (m *EnvironmentStatus) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

func (m *EnvironmentStatus) GetConstants() *ConstantFetcherStatus {
	if m != nil {
		return m.Constants
	}
	return nil
}

func (m *EnvironmentStatus) GetKernelLockdown() string {
	if m != nil {
		return m.KernelLockdown
	}
	return ""
}

type StorageRequestParams struct {
	LocalStorageDirectory    string   `protobuf:"bytes,1,opt,name=LocalStorageDirectory,proto3" json:"LocalStorageDirectory,omitempty"`
	LocalStorageFormats      []string `protobuf:"bytes,2,rep,name=LocalStorageFormats,proto3" json:"LocalStorageFormats,omitempty"`
	LocalStorageCompression  bool     `protobuf:"varint,3,opt,name=LocalStorageCompression,proto3" json:"LocalStorageCompression,omitempty"`
	RemoteStorageFormats     []string `protobuf:"bytes,4,rep,name=RemoteStorageFormats,proto3" json:"RemoteStorageFormats,omitempty"`
	RemoteStorageCompression bool     `protobuf:"varint,5,opt,name=RemoteStorageCompression,proto3" json:"RemoteStorageCompression,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *StorageRequestParams) Reset()         { *m = StorageRequestParams{} }
func (m *StorageRequestParams) String() string { return proto.CompactTextString(m) }
func (*StorageRequestParams) ProtoMessage()    {}
func (*StorageRequestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{18}
}

func (m *StorageRequestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageRequestParams.Unmarshal(m, b)
}
func (m *StorageRequestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageRequestParams.Marshal(b, m, deterministic)
}
func (m *StorageRequestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageRequestParams.Merge(m, src)
}
func (m *StorageRequestParams) XXX_Size() int {
	return xxx_messageInfo_StorageRequestParams.Size(m)
}
func (m *StorageRequestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageRequestParams.DiscardUnknown(m)
}

var xxx_messageInfo_StorageRequestParams proto.InternalMessageInfo

func (m *StorageRequestParams) GetLocalStorageDirectory() string {
	if m != nil {
		return m.LocalStorageDirectory
	}
	return ""
}

func (m *StorageRequestParams) GetLocalStorageFormats() []string {
	if m != nil {
		return m.LocalStorageFormats
	}
	return nil
}

func (m *StorageRequestParams) GetLocalStorageCompression() bool {
	if m != nil {
		return m.LocalStorageCompression
	}
	return false
}

func (m *StorageRequestParams) GetRemoteStorageFormats() []string {
	if m != nil {
		return m.RemoteStorageFormats
	}
	return nil
}

func (m *StorageRequestParams) GetRemoteStorageCompression() bool {
	if m != nil {
		return m.RemoteStorageCompression
	}
	return false
}

type DumpActivityParams struct {
	Comm                 string                `protobuf:"bytes,1,opt,name=comm,proto3" json:"comm,omitempty"`
	Timeout              int32                 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	DifferentiateArgs    bool                  `protobuf:"varint,4,opt,name=DifferentiateArgs,proto3" json:"DifferentiateArgs,omitempty"`
	Storage              *StorageRequestParams `protobuf:"bytes,5,opt,name=Storage,proto3" json:"Storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DumpActivityParams) Reset()         { *m = DumpActivityParams{} }
func (m *DumpActivityParams) String() string { return proto.CompactTextString(m) }
func (*DumpActivityParams) ProtoMessage()    {}
func (*DumpActivityParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{19}
}

func (m *DumpActivityParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpActivityParams.Unmarshal(m, b)
}
func (m *DumpActivityParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpActivityParams.Marshal(b, m, deterministic)
}
func (m *DumpActivityParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpActivityParams.Merge(m, src)
}
func (m *DumpActivityParams) XXX_Size() int {
	return xxx_messageInfo_DumpActivityParams.Size(m)
}
func (m *DumpActivityParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpActivityParams.DiscardUnknown(m)
}

var xxx_messageInfo_DumpActivityParams proto.InternalMessageInfo

func (m *DumpActivityParams) GetComm() string {
	if m != nil {
		return m.Comm
	}
	return ""
}

func (m *DumpActivityParams) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *DumpActivityParams) GetDifferentiateArgs() bool {
	if m != nil {
		return m.DifferentiateArgs
	}
	return false
}

func (m *DumpActivityParams) GetStorage() *StorageRequestParams {
	if m != nil {
		return m.Storage
	}
	return nil
}

type StorageRequestMessage struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Format               string   `protobuf:"bytes,2,opt,name=Format,proto3" json:"Format,omitempty"`
	Compression          bool     `protobuf:"varint,3,opt,name=Compression,proto3" json:"Compression,omitempty"`
	File                 string   `protobuf:"bytes,4,opt,name=File,proto3" json:"File,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageRequestMessage) Reset()         { *m = StorageRequestMessage{} }
func (m *StorageRequestMessage) String() string { return proto.CompactTextString(m) }
func (*StorageRequestMessage) ProtoMessage()    {}
func (*StorageRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{20}
}

func (m *StorageRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageRequestMessage.Unmarshal(m, b)
}
func (m *StorageRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageRequestMessage.Marshal(b, m, deterministic)
}
func (m *StorageRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageRequestMessage.Merge(m, src)
}
func (m *StorageRequestMessage) XXX_Size() int {
	return xxx_messageInfo_StorageRequestMessage.Size(m)
}
func (m *StorageRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StorageRequestMessage proto.InternalMessageInfo

func (m *StorageRequestMessage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StorageRequestMessage) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *StorageRequestMessage) GetCompression() bool {
	if m != nil {
		return m.Compression
	}
	return false
}

func (m *StorageRequestMessage) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

type SecurityActivityDumpMessage struct {
	Comm                 string                   `protobuf:"bytes,1,opt,name=Comm,proto3" json:"Comm,omitempty"`
	ContainerID          string                   `protobuf:"bytes,2,opt,name=ContainerID,proto3" json:"ContainerID,omitempty"`
	Tags                 []string                 `protobuf:"bytes,3,rep,name=Tags,proto3" json:"Tags,omitempty"`
	DifferentiateArgs    bool                     `protobuf:"varint,4,opt,name=DifferentiateArgs,proto3" json:"DifferentiateArgs,omitempty"`
	Timeout              string                   `protobuf:"bytes,5,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Start                string                   `protobuf:"bytes,6,opt,name=Start,proto3" json:"Start,omitempty"`
	Left                 string                   `protobuf:"bytes,7,opt,name=Left,proto3" json:"Left,omitempty"`
	Error                string                   `protobuf:"bytes,8,opt,name=Error,proto3" json:"Error,omitempty"`
	Storage              []*StorageRequestMessage `protobuf:"bytes,9,rep,name=Storage,proto3" json:"Storage,omitempty"`
	Name                 string                   `protobuf:"bytes,10,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SecurityActivityDumpMessage) Reset()         { *m = SecurityActivityDumpMessage{} }
func (m *SecurityActivityDumpMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityActivityDumpMessage) ProtoMessage()    {}
func (*SecurityActivityDumpMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{21}
}

func (m *SecurityActivityDumpMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityActivityDumpMessage.Unmarshal(m, b)
}
func (m *SecurityActivityDumpMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityActivityDumpMessage.Marshal(b, m, deterministic)
}
func (m *SecurityActivityDumpMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityActivityDumpMessage.Merge(m, src)
}
func (m *SecurityActivityDumpMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityActivityDumpMessage.Size(m)
}
func (m *SecurityActivityDumpMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityActivityDumpMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityActivityDumpMessage proto.InternalMessageInfo

func (m *SecurityActivityDumpMessage) GetComm() string {
	if m != nil {
		return m.Comm
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetContainerID() string {
	if m != nil {
		return m.ContainerID
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SecurityActivityDumpMessage) GetDifferentiateArgs() bool {
	if m != nil {
		return m.DifferentiateArgs
	}
	return false
}

func (m *SecurityActivityDumpMessage) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetLeft() string {
	if m != nil {
		return m.Left
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetStorage() []*StorageRequestMessage {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *SecurityActivityDumpMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListActivityDumpsParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListActivityDumpsParams) Reset()         { *m = ListActivityDumpsParams{} }
func (m *ListActivityDumpsParams) String() string { return proto.CompactTextString(m) }
func (*ListActivityDumpsParams) ProtoMessage()    {}
func (*ListActivityDumpsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{22}
}

func (m *ListActivityDumpsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActivityDumpsParams.Unmarshal(m, b)
}
func (m *ListActivityDumpsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActivityDumpsParams.Marshal(b, m, deterministic)
}
func (m *ListActivityDumpsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActivityDumpsParams.Merge(m, src)
}
func (m *ListActivityDumpsParams) XXX_Size() int {
	return xxx_messageInfo_ListActivityDumpsParams.Size(m)
}
func (m *ListActivityDumpsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActivityDumpsParams.DiscardUnknown(m)
}

var xxx_messageInfo_ListActivityDumpsParams proto.InternalMessageInfo

type SecurityActivityDumpListMessage struct {
	Dumps                []*SecurityActivityDumpMessage `protobuf:"bytes,1,rep,name=Dumps,proto3" json:"Dumps,omitempty"`
	Error                string                         `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SecurityActivityDumpListMessage) Reset()         { *m = SecurityActivityDumpListMessage{} }
func (m *SecurityActivityDumpListMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityActivityDumpListMessage) ProtoMessage()    {}
func (*SecurityActivityDumpListMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{23}
}

func (m *SecurityActivityDumpListMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityActivityDumpListMessage.Unmarshal(m, b)
}
func (m *SecurityActivityDumpListMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityActivityDumpListMessage.Marshal(b, m, deterministic)
}
func (m *SecurityActivityDumpListMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityActivityDumpListMessage.Merge(m, src)
}
func (m *SecurityActivityDumpListMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityActivityDumpListMessage.Size(m)
}
func (m *SecurityActivityDumpListMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityActivityDumpListMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityActivityDumpListMessage proto.InternalMessageInfo

func (m *SecurityActivityDumpListMessage) GetDumps() []*SecurityActivityDumpMessage {
	if m != nil {
		return m.Dumps
	}
	return nil
}

func (m *SecurityActivityDumpListMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type StopActivityDumpParams struct {
	Comm                 string   `protobuf:"bytes,2,opt,name=Comm,proto3" json:"Comm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopActivityDumpParams) Reset()         { *m = StopActivityDumpParams{} }
func (m *StopActivityDumpParams) String() string { return proto.CompactTextString(m) }
func (*StopActivityDumpParams) ProtoMessage()    {}
func (*StopActivityDumpParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{24}
}

func (m *StopActivityDumpParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopActivityDumpParams.Unmarshal(m, b)
}
func (m *StopActivityDumpParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopActivityDumpParams.Marshal(b, m, deterministic)
}
func (m *StopActivityDumpParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopActivityDumpParams.Merge(m, src)
}
func (m *StopActivityDumpParams) XXX_Size() int {
	return xxx_messageInfo_StopActivityDumpParams.Size(m)
}
func (m *StopActivityDumpParams) XXX_DiscardUnknown() {
	xxx_messageInfo_StopActivityDumpParams.DiscardUnknown(m)
}

var xxx_messageInfo_StopActivityDumpParams proto.InternalMessageInfo

func (m *StopActivityDumpParams) GetComm() string {
	if m != nil {
		return m.Comm
	}
	return ""
}

type SecurityActivityDumpStoppedMessage struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityActivityDumpStoppedMessage) Reset()         { *m = SecurityActivityDumpStoppedMessage{} }
func (m *SecurityActivityDumpStoppedMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityActivityDumpStoppedMessage) ProtoMessage()    {}
func (*SecurityActivityDumpStoppedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{25}
}

func (m *SecurityActivityDumpStoppedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityActivityDumpStoppedMessage.Unmarshal(m, b)
}
func (m *SecurityActivityDumpStoppedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityActivityDumpStoppedMessage.Marshal(b, m, deterministic)
}
func (m *SecurityActivityDumpStoppedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityActivityDumpStoppedMessage.Merge(m, src)
}
func (m *SecurityActivityDumpStoppedMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityActivityDumpStoppedMessage.Size(m)
}
func (m *SecurityActivityDumpStoppedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityActivityDumpStoppedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityActivityDumpStoppedMessage proto.InternalMessageInfo

func (m *SecurityActivityDumpStoppedMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type TranscodingRequestParams struct {
	ActivityDumpFile     string                `protobuf:"bytes,1,opt,name=ActivityDumpFile,proto3" json:"ActivityDumpFile,omitempty"`
	Storage              *StorageRequestParams `protobuf:"bytes,2,opt,name=Storage,proto3" json:"Storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TranscodingRequestParams) Reset()         { *m = TranscodingRequestParams{} }
func (m *TranscodingRequestParams) String() string { return proto.CompactTextString(m) }
func (*TranscodingRequestParams) ProtoMessage()    {}
func (*TranscodingRequestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{26}
}

func (m *TranscodingRequestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscodingRequestParams.Unmarshal(m, b)
}
func (m *TranscodingRequestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscodingRequestParams.Marshal(b, m, deterministic)
}
func (m *TranscodingRequestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscodingRequestParams.Merge(m, src)
}
func (m *TranscodingRequestParams) XXX_Size() int {
	return xxx_messageInfo_TranscodingRequestParams.Size(m)
}
func (m *TranscodingRequestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscodingRequestParams.DiscardUnknown(m)
}

var xxx_messageInfo_TranscodingRequestParams proto.InternalMessageInfo

func (m *TranscodingRequestParams) GetActivityDumpFile() string {
	if m != nil {
		return m.ActivityDumpFile
	}
	return ""
}

func (m *TranscodingRequestParams) GetStorage() *StorageRequestParams {
	if m != nil {
		return m.Storage
	}
	return nil
}

type TranscodingRequestMessage struct {
	Error                string                   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Storage              []*StorageRequestMessage `protobuf:"bytes,2,rep,name=Storage,proto3" json:"Storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TranscodingRequestMessage) Reset()         { *m = TranscodingRequestMessage{} }
func (m *TranscodingRequestMessage) String() string { return proto.CompactTextString(m) }
func (*TranscodingRequestMessage) ProtoMessage()    {}
func (*TranscodingRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{27}
}

func (m *TranscodingRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscodingRequestMessage.Unmarshal(m, b)
}
func (m *TranscodingRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscodingRequestMessage.Marshal(b, m, deterministic)
}
func (m *TranscodingRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscodingRequestMessage.Merge(m, src)
}
func (m *TranscodingRequestMessage) XXX_Size() int {
	return xxx_messageInfo_TranscodingRequestMessage.Size(m)
}
func (m *TranscodingRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscodingRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TranscodingRequestMessage proto.InternalMessageInfo

func (m *TranscodingRequestMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *TranscodingRequestMessage) GetStorage() []*StorageRequestMessage {
	if m != nil {
		return m.Storage
	}
	return nil
}

func init() {
	proto.RegisterType((*GetEventParams)(nil), "api.GetEventParams")
	proto.RegisterType((*SecurityEventMessage)(nil), "api.SecurityEventMessage")
	proto.RegisterType((*DumpProcessCacheParams)(nil), "api.DumpProcessCacheParams")
	proto.RegisterType((*SecurityDumpProcessCacheMessage)(nil), "api.SecurityDumpProcessCacheMessage")
	proto.RegisterType((*DumpNetworkNamespaceParams)(nil), "api.DumpNetworkNamespaceParams")
	proto.RegisterType((*DumpNetworkNamespaceMessage)(nil), "api.DumpNetworkNamespaceMessage")
	proto.RegisterType((*GetConfigParams)(nil), "api.GetConfigParams")
	proto.RegisterType((*SecurityConfigMessage)(nil), "api.SecurityConfigMessage")
	proto.RegisterType((*RunSelfTestParams)(nil), "api.RunSelfTestParams")
	proto.RegisterType((*ReloadPoliciesParams)(nil), "api.ReloadPoliciesParams")
	proto.RegisterType((*ReloadPoliciesResultMessage)(nil), "api.ReloadPoliciesResultMessage")
	proto.RegisterType((*SecuritySelfTestResultMessage)(nil), "api.SecuritySelfTestResultMessage")
	proto.RegisterType((*GetStatusParams)(nil), "api.GetStatusParams")
	proto.RegisterType((*ConstantValueAndSource)(nil), "api.ConstantValueAndSource")
	proto.RegisterType((*SelfTestsStatus)(nil), "api.SelfTestsStatus")
	proto.RegisterType((*Status)(nil), "api.Status")
	proto.RegisterType((*ConstantFetcherStatus)(nil), "api.ConstantFetcherStatus")
	proto.RegisterType((*EnvironmentStatus)(nil), "api.EnvironmentStatus")
	proto.RegisterType((*StorageRequestParams)(nil), "api.StorageRequestParams")
	proto.RegisterType((*DumpActivityParams)(nil), "api.DumpActivityParams")
	proto.RegisterType((*StorageRequestMessage)(nil), "api.StorageRequestMessage")
	proto.RegisterType((*SecurityActivityDumpMessage)(nil), "api.SecurityActivityDumpMessage")
	proto.RegisterType((*ListActivityDumpsParams)(nil), "api.ListActivityDumpsParams")
	proto.RegisterType((*SecurityActivityDumpListMessage)(nil), "api.SecurityActivityDumpListMessage")
	proto.RegisterType((*StopActivityDumpParams)(nil), "api.StopActivityDumpParams")
	proto.RegisterType((*SecurityActivityDumpStoppedMessage)(nil), "api.SecurityActivityDumpStoppedMessage")
	proto.RegisterType((*TranscodingRequestParams)(nil), "api.TranscodingRequestParams")
	proto.RegisterType((*TranscodingRequestMessage)(nil), "api.TranscodingRequestMessage")
}

func init() { proto.RegisterFile("pkg/security/api/api.proto", fileDescriptor_ce049ba84fb5261a) }

var fileDescriptor_ce049ba84fb5261a = []byte{
	// 1304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xeb, 0x6e, 0x13, 0x47,
	0x14, 0x76, 0x36, 0xf7, 0x63, 0x1a, 0x92, 0xc1, 0x09, 0x9b, 0x4d, 0x81, 0x68, 0x84, 0x5a, 0x54,
	0x21, 0x40, 0x06, 0x55, 0x08, 0xa9, 0xaa, 0x68, 0x9c, 0xa0, 0x08, 0x03, 0xd1, 0x3a, 0x05, 0x95,
	0xfe, 0xa8, 0x86, 0xf5, 0xd8, 0x5e, 0x65, 0x77, 0x67, 0x3b, 0x3b, 0x1b, 0x14, 0x55, 0x7d, 0x88,
	0x3e, 0x44, 0xa5, 0xbe, 0x42, 0x9f, 0xab, 0x2f, 0x50, 0xcd, 0x6d, 0x3d, 0x6b, 0xaf, 0x29, 0xfd,
	0x61, 0x69, 0xcf, 0x65, 0xce, 0xf9, 0xe6, 0xdc, 0xe6, 0x18, 0x82, 0xfc, 0x62, 0xfc, 0xb0, 0xa0,
	0x51, 0xc9, 0x63, 0x71, 0xf5, 0x90, 0xe4, 0xb1, 0xfc, 0x3d, 0xc8, 0x39, 0x13, 0x0c, 0x2d, 0x93,
	0x3c, 0xc6, 0xdb, 0xb0, 0xf5, 0x82, 0x8a, 0xe3, 0x4b, 0x9a, 0x89, 0x33, 0xc2, 0x49, 0x5a, 0xe0,
	0x1c, 0x3a, 0x03, 0x73, 0x40, 0xb1, 0x5f, 0xd1, 0xa2, 0x20, 0x63, 0x8a, 0xf6, 0x60, 0x2d, 0x2c,
	0x13, 0x7a, 0xda, 0xf3, 0x97, 0x0e, 0x97, 0xee, 0x6d, 0x86, 0x86, 0x42, 0x08, 0x56, 0x7a, 0x44,
	0x10, 0xdf, 0x3b, 0x5c, 0xba, 0x77, 0x2d, 0x54, 0xdf, 0x92, 0x77, 0x4e, 0xc6, 0x85, 0xbf, 0x7c,
	0xb8, 0x7c, 0x6f, 0x33, 0x54, 0xdf, 0xc8, 0x87, 0xf5, 0x01, 0xe5, 0x97, 0x71, 0x44, 0xfd, 0x15,
	0x65, 0xc0, 0x92, 0xf8, 0x09, 0xec, 0xf5, 0xca, 0x34, 0x3f, 0xe3, 0x2c, 0xa2, 0x45, 0x71, 0x44,
	0xa2, 0x09, 0xd5, 0x58, 0x50, 0x00, 0x1b, 0xef, 0x62, 0x31, 0x79, 0xce, 0xc7, 0x85, 0xf2, 0xba,
	0x11, 0x56, 0x34, 0xfe, 0x0e, 0xee, 0x58, 0x9c, 0xb3, 0xa7, 0x2d, 0xe4, 0x00, 0x36, 0x4e, 0xe2,
	0x84, 0x66, 0x24, 0xa5, 0x06, 0x74, 0x45, 0xe3, 0x3e, 0x04, 0xf2, 0xd8, 0x6b, 0x2a, 0x3e, 0x32,
	0x7e, 0xf1, 0x9a, 0xa4, 0xb4, 0xc8, 0x49, 0x64, 0x1d, 0x3f, 0x00, 0x34, 0xc8, 0x48, 0x5e, 0x4c,
	0x98, 0x38, 0xcd, 0x04, 0xe5, 0x23, 0x12, 0x51, 0x0b, 0xa1, 0x41, 0x82, 0x7f, 0x87, 0x83, 0x26,
	0x6b, 0x16, 0x48, 0x07, 0x56, 0x29, 0xe7, 0x8c, 0x1b, 0x14, 0x9a, 0x40, 0x18, 0xae, 0xc9, 0x43,
	0x15, 0x44, 0x4f, 0x09, 0x6b, 0x3c, 0x74, 0x17, 0xbe, 0x78, 0xc1, 0x49, 0x3e, 0xa9, 0x94, 0x96,
	0x95, 0x52, 0x9d, 0x89, 0x77, 0xe0, 0xfa, 0x0b, 0x2a, 0x8e, 0x58, 0x36, 0x8a, 0xc7, 0x26, 0x8d,
	0xbf, 0xc0, 0xae, 0x0d, 0x8f, 0xe6, 0x5b, 0x2c, 0x5f, 0xc1, 0x56, 0x58, 0x66, 0x22, 0x4e, 0xe9,
	0x71, 0x46, 0x3e, 0x24, 0x74, 0x68, 0xae, 0x35, 0xc3, 0x45, 0xb7, 0x01, 0x4e, 0x4e, 0x5f, 0x59,
	0x1d, 0x4f, 0xe9, 0x38, 0x1c, 0x7c, 0x03, 0x76, 0xc2, 0x32, 0x1b, 0xd0, 0x64, 0x74, 0x4e, 0x0b,
	0x5b, 0x3c, 0x7b, 0xd0, 0x09, 0x69, 0xc2, 0xc8, 0xf0, 0x8c, 0x25, 0x71, 0x14, 0xd3, 0xc2, 0xf0,
	0x6f, 0xc1, 0x41, 0x9d, 0x1f, 0xd2, 0xa2, 0x4c, 0x6c, 0x6d, 0xe1, 0x63, 0xb8, 0x65, 0xc1, 0x5a,
	0x83, 0x35, 0x05, 0xb4, 0x05, 0xde, 0x9b, 0x0b, 0x03, 0xd4, 0x7b, 0x73, 0x21, 0x03, 0x7a, 0xac,
	0x02, 0xaa, 0x63, 0xa6, 0x09, 0x13, 0x86, 0x81, 0x20, 0xa2, 0xb4, 0x8e, 0xdf, 0xc2, 0xde, 0x11,
	0xcb, 0x0a, 0x41, 0x32, 0xf1, 0x96, 0x24, 0x25, 0x7d, 0x9e, 0x0d, 0x07, 0xac, 0xe4, 0x91, 0x32,
	0x59, 0xd5, 0xb2, 0x77, 0xda, 0x93, 0x26, 0x95, 0x86, 0x32, 0xb9, 0x12, 0x6a, 0x42, 0x56, 0xbd,
	0xd6, 0x37, 0x81, 0x37, 0x14, 0x1e, 0xc3, 0x75, 0x8b, 0xb4, 0xd0, 0x0e, 0x65, 0xaa, 0xfa, 0xa4,
	0x10, 0xe7, 0x71, 0x4a, 0x0b, 0x41, 0xd2, 0xdc, 0xd8, 0xae, 0x33, 0x55, 0x1b, 0x94, 0x91, 0x2c,
	0x55, 0xdf, 0x53, 0xdd, 0x61, 0x49, 0x09, 0xe0, 0x84, 0xc4, 0x89, 0xed, 0x1a, 0x4d, 0xe0, 0x4b,
	0x58, 0x33, 0xf6, 0x9f, 0x42, 0xfb, 0x38, 0xbb, 0x8c, 0x39, 0xcb, 0x52, 0x9a, 0x09, 0x65, 0xbd,
	0xdd, 0xdd, 0x7b, 0x20, 0x1b, 0xda, 0xe1, 0x6b, 0xe5, 0xd0, 0x55, 0x45, 0x5d, 0xd8, 0xac, 0xc0,
	0xaa, 0xeb, 0xb5, 0xbb, 0x1d, 0x75, 0x6e, 0xe6, 0x0a, 0xe1, 0x54, 0x0d, 0x4f, 0x60, 0xd7, 0x06,
	0xee, 0x84, 0x8a, 0x68, 0x42, 0xb9, 0x81, 0x21, 0x9b, 0x4a, 0x33, 0x64, 0x43, 0x2c, 0xab, 0xa6,
	0x32, 0x34, 0x7a, 0x0c, 0x6b, 0x2a, 0x6c, 0xfa, 0x6e, 0xed, 0xee, 0x81, 0xf2, 0xd2, 0x9c, 0x80,
	0xd0, 0xa8, 0xe2, 0x3f, 0x96, 0x60, 0x67, 0xee, 0x02, 0xaa, 0xf5, 0x09, 0xcf, 0xe2, 0x6c, 0x5c,
	0xb9, 0xb1, 0x34, 0x7a, 0x0a, 0x9b, 0xd6, 0xa6, 0xbd, 0x4f, 0x50, 0xf3, 0x54, 0x43, 0x1c, 0x4e,
	0x95, 0x65, 0xf1, 0xbf, 0xa4, 0x3c, 0xa3, 0x49, 0x9f, 0x45, 0x17, 0x43, 0xf6, 0x31, 0x33, 0x69,
	0x9d, 0xe1, 0xe2, 0xbf, 0x3c, 0xe8, 0x0c, 0x04, 0xe3, 0x64, 0x4c, 0x43, 0xfa, 0x6b, 0x59, 0x15,
	0x38, 0x7a, 0x02, 0xbb, 0x7d, 0x16, 0x91, 0xc4, 0x08, 0x7b, 0x31, 0xa7, 0x91, 0x60, 0xfc, 0xca,
	0x24, 0xbb, 0x59, 0x88, 0x1e, 0xc1, 0x0d, 0x57, 0x70, 0xc2, 0x78, 0x4a, 0x84, 0x2d, 0x80, 0x26,
	0x11, 0x7a, 0x0a, 0x37, 0x5d, 0xf6, 0x11, 0x4b, 0x73, 0x4e, 0x8b, 0x22, 0x66, 0x1a, 0xf1, 0x46,
	0xb8, 0x48, 0x8c, 0xba, 0xb2, 0x05, 0x53, 0x26, 0xe8, 0x8c, 0xb3, 0x15, 0xe5, 0xac, 0x51, 0x86,
	0x9e, 0x81, 0x5f, 0xe3, 0xbb, 0xee, 0x56, 0x95, 0xbb, 0x85, 0x72, 0xfc, 0xe7, 0x12, 0x20, 0x39,
	0xb2, 0x9e, 0x47, 0x22, 0xbe, 0x8c, 0xc5, 0x95, 0x09, 0x14, 0x82, 0x95, 0x88, 0xa5, 0xa9, 0x89,
	0x8b, 0xfa, 0x96, 0xb5, 0x2f, 0x27, 0x0c, 0x2b, 0x85, 0xca, 0xda, 0x6a, 0x68, 0x49, 0x74, 0x1f,
	0x76, 0x7a, 0xf1, 0x68, 0x44, 0x39, 0xcd, 0x44, 0x4c, 0x04, 0x55, 0x13, 0x7f, 0x45, 0x79, 0x9e,
	0x17, 0xa0, 0xc7, 0xb0, 0x6e, 0x80, 0x28, 0x74, 0xed, 0xee, 0xbe, 0xae, 0xe6, 0x86, 0x84, 0x85,
	0x56, 0x13, 0x5f, 0xc1, 0x6e, 0x5d, 0xc1, 0xce, 0x16, 0xf9, 0x58, 0x5d, 0xe5, 0xf6, 0x85, 0x50,
	0xdf, 0xb2, 0xed, 0x75, 0x6c, 0xcc, 0x80, 0x31, 0x14, 0x3a, 0x84, 0xf6, 0x7c, 0x2a, 0x5c, 0x96,
	0xb4, 0x26, 0xc7, 0xb2, 0x79, 0xe3, 0xd4, 0x37, 0xfe, 0xdb, 0x83, 0x03, 0x3b, 0xdf, 0x6c, 0x98,
	0x64, 0xc8, 0x1c, 0x04, 0x47, 0x4e, 0xac, 0xe4, 0xb7, 0xf6, 0x94, 0x09, 0x12, 0x67, 0x94, 0x9f,
	0xf6, 0x0c, 0x0c, 0x97, 0xd5, 0xf8, 0xc8, 0xfe, 0xbf, 0x38, 0xfa, 0xb0, 0x7e, 0x6e, 0xf2, 0xb1,
	0xaa, 0x9f, 0x64, 0x43, 0xca, 0x59, 0x34, 0x10, 0x84, 0x0b, 0x7f, 0x4d, 0xcf, 0x57, 0x45, 0x48,
	0x8f, 0x7d, 0x3a, 0x12, 0xfe, 0xba, 0xc6, 0x29, 0xbf, 0xa7, 0x93, 0x78, 0xc3, 0x99, 0xc4, 0xe8,
	0xc9, 0x34, 0x43, 0x9b, 0x6a, 0x12, 0x04, 0x0d, 0x19, 0x32, 0xd7, 0xaf, 0x52, 0x24, 0xed, 0xcb,
	0xa7, 0xd3, 0x07, 0x6d, 0x5f, 0x7e, 0xe3, 0x7d, 0xb8, 0xd9, 0x8f, 0x0b, 0xe1, 0x86, 0xcd, 0xce,
	0x76, 0x36, 0xdd, 0x00, 0x5c, 0xb1, 0x54, 0xb7, 0x91, 0xfd, 0x16, 0x56, 0xd5, 0x09, 0x35, 0x42,
	0xda, 0xdd, 0x43, 0x33, 0xf5, 0x16, 0xa6, 0x22, 0xd4, 0xea, 0x0b, 0xde, 0x97, 0xfb, 0xb0, 0x37,
	0x10, 0x2c, 0x77, 0xcf, 0x4d, 0xab, 0x5d, 0x65, 0xd0, 0x9b, 0x66, 0x10, 0x3f, 0x03, 0xdc, 0xe4,
	0x49, 0x5a, 0xc8, 0xe9, 0xd0, 0x59, 0x0d, 0x8e, 0xdd, 0xd5, 0x40, 0x7b, 0xfa, 0x0d, 0xfc, 0x73,
	0x4e, 0xb2, 0x22, 0x62, 0xc3, 0x38, 0x1b, 0xd7, 0x47, 0xd0, 0x37, 0xb0, 0xed, 0xda, 0x53, 0xd5,
	0xa6, 0x0f, 0xcf, 0xf1, 0xdd, 0x4e, 0xf1, 0x3e, 0xbb, 0x53, 0xc6, 0xb0, 0x3f, 0xef, 0xfc, 0x93,
	0x78, 0xdd, 0x7c, 0x7b, 0x9f, 0x9d, 0xef, 0xee, 0x3f, 0x6b, 0xb0, 0x65, 0x43, 0xf4, 0x8a, 0x0d,
	0xcb, 0x84, 0xa2, 0xef, 0x61, 0xd3, 0xee, 0xa3, 0x05, 0xba, 0xa1, 0x8c, 0xd4, 0xf7, 0xd3, 0x60,
	0xbf, 0x96, 0x43, 0x77, 0x45, 0xc5, 0xad, 0x47, 0x4b, 0xe8, 0x1d, 0x6c, 0xcf, 0xae, 0x83, 0x48,
	0x3f, 0x43, 0xcd, 0x3b, 0x66, 0x70, 0xb7, 0x66, 0x6f, 0xc1, 0x2a, 0x89, 0x5b, 0x06, 0x99, 0xde,
	0xa5, 0x50, 0xc7, 0x22, 0x73, 0x77, 0xae, 0x20, 0xa8, 0x99, 0xaa, 0xad, 0x5d, 0xb8, 0x85, 0x1e,
	0x29, 0x03, 0xe6, 0x79, 0xab, 0x0c, 0xb8, 0xdb, 0x4a, 0xd0, 0x36, 0x51, 0x93, 0x2c, 0xdc, 0x42,
	0x2f, 0xa1, 0xed, 0xac, 0x58, 0x48, 0xbf, 0xf5, 0x73, 0x4b, 0x57, 0x80, 0x6b, 0x6e, 0x1b, 0x17,
	0x28, 0xdc, 0x42, 0x6f, 0x60, 0xab, 0xbe, 0x82, 0x21, 0x1d, 0xc9, 0xa6, 0x7d, 0x2d, 0x38, 0x6c,
	0x10, 0xcd, 0x1a, 0xfc, 0x19, 0x3a, 0x4d, 0x3b, 0x2f, 0xba, 0x53, 0x45, 0xbb, 0x79, 0xb9, 0x36,
	0xc6, 0x3f, 0xb1, 0x2f, 0xab, 0xab, 0x5f, 0x73, 0x1f, 0x15, 0x74, 0xb3, 0x3a, 0x53, 0x7f, 0x67,
	0x82, 0xff, 0x6c, 0x69, 0xdc, 0x42, 0x3f, 0xc1, 0xce, 0xdc, 0x0c, 0x41, 0x5f, 0xaa, 0x83, 0x0b,
	0x66, 0xcb, 0x4c, 0x55, 0x2c, 0x18, 0x2f, 0xb8, 0x85, 0xde, 0xc3, 0xf6, 0xec, 0x48, 0x30, 0xe5,
	0xd6, 0x3c, 0x29, 0x82, 0xaf, 0x17, 0x1a, 0xae, 0x0f, 0x06, 0xdc, 0x42, 0x3f, 0x02, 0x9a, 0xef,
	0x43, 0x74, 0x4b, 0x19, 0x58, 0x34, 0x1d, 0x82, 0xdb, 0x0b, 0xc4, 0x95, 0xd9, 0x1f, 0xd0, 0xfb,
	0xed, 0xd9, 0x7f, 0x85, 0x1f, 0xd6, 0xd4, 0x5f, 0xc2, 0xc7, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x40, 0xfd, 0x01, 0x79, 0x30, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecurityModuleClient is the client API for SecurityModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecurityModuleClient interface {
	GetEvents(ctx context.Context, in *GetEventParams, opts ...grpc.CallOption) (SecurityModule_GetEventsClient, error)
	DumpProcessCache(ctx context.Context, in *DumpProcessCacheParams, opts ...grpc.CallOption) (*SecurityDumpProcessCacheMessage, error)
	GetConfig(ctx context.Context, in *GetConfigParams, opts ...grpc.CallOption) (*SecurityConfigMessage, error)
	GetStatus(ctx context.Context, in *GetStatusParams, opts ...grpc.CallOption) (*Status, error)
	RunSelfTest(ctx context.Context, in *RunSelfTestParams, opts ...grpc.CallOption) (*SecuritySelfTestResultMessage, error)
	ReloadPolicies(ctx context.Context, in *ReloadPoliciesParams, opts ...grpc.CallOption) (*ReloadPoliciesResultMessage, error)
	DumpNetworkNamespace(ctx context.Context, in *DumpNetworkNamespaceParams, opts ...grpc.CallOption) (*DumpNetworkNamespaceMessage, error)
	// Activity dumps
	DumpActivity(ctx context.Context, in *DumpActivityParams, opts ...grpc.CallOption) (*SecurityActivityDumpMessage, error)
	ListActivityDumps(ctx context.Context, in *ListActivityDumpsParams, opts ...grpc.CallOption) (*SecurityActivityDumpListMessage, error)
	StopActivityDump(ctx context.Context, in *StopActivityDumpParams, opts ...grpc.CallOption) (*SecurityActivityDumpStoppedMessage, error)
	TranscodingRequest(ctx context.Context, in *TranscodingRequestParams, opts ...grpc.CallOption) (*TranscodingRequestMessage, error)
}

type securityModuleClient struct {
	cc *grpc.ClientConn
}

func NewSecurityModuleClient(cc *grpc.ClientConn) SecurityModuleClient {
	return &securityModuleClient{cc}
}

func (c *securityModuleClient) GetEvents(ctx context.Context, in *GetEventParams, opts ...grpc.CallOption) (SecurityModule_GetEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SecurityModule_serviceDesc.Streams[0], "/api.SecurityModule/GetEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &securityModuleGetEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SecurityModule_GetEventsClient interface {
	Recv() (*SecurityEventMessage, error)
	grpc.ClientStream
}

type securityModuleGetEventsClient struct {
	grpc.ClientStream
}

func (x *securityModuleGetEventsClient) Recv() (*SecurityEventMessage, error) {
	m := new(SecurityEventMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *securityModuleClient) DumpProcessCache(ctx context.Context, in *DumpProcessCacheParams, opts ...grpc.CallOption) (*SecurityDumpProcessCacheMessage, error) {
	out := new(SecurityDumpProcessCacheMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/DumpProcessCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) GetConfig(ctx context.Context, in *GetConfigParams, opts ...grpc.CallOption) (*SecurityConfigMessage, error) {
	out := new(SecurityConfigMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) GetStatus(ctx context.Context, in *GetStatusParams, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) RunSelfTest(ctx context.Context, in *RunSelfTestParams, opts ...grpc.CallOption) (*SecuritySelfTestResultMessage, error) {
	out := new(SecuritySelfTestResultMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/RunSelfTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) ReloadPolicies(ctx context.Context, in *ReloadPoliciesParams, opts ...grpc.CallOption) (*ReloadPoliciesResultMessage, error) {
	out := new(ReloadPoliciesResultMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/ReloadPolicies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) DumpNetworkNamespace(ctx context.Context, in *DumpNetworkNamespaceParams, opts ...grpc.CallOption) (*DumpNetworkNamespaceMessage, error) {
	out := new(DumpNetworkNamespaceMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/DumpNetworkNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) DumpActivity(ctx context.Context, in *DumpActivityParams, opts ...grpc.CallOption) (*SecurityActivityDumpMessage, error) {
	out := new(SecurityActivityDumpMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/DumpActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) ListActivityDumps(ctx context.Context, in *ListActivityDumpsParams, opts ...grpc.CallOption) (*SecurityActivityDumpListMessage, error) {
	out := new(SecurityActivityDumpListMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/ListActivityDumps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) StopActivityDump(ctx context.Context, in *StopActivityDumpParams, opts ...grpc.CallOption) (*SecurityActivityDumpStoppedMessage, error) {
	out := new(SecurityActivityDumpStoppedMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/StopActivityDump", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) TranscodingRequest(ctx context.Context, in *TranscodingRequestParams, opts ...grpc.CallOption) (*TranscodingRequestMessage, error) {
	out := new(TranscodingRequestMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/TranscodingRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityModuleServer is the server API for SecurityModule service.
type SecurityModuleServer interface {
	GetEvents(*GetEventParams, SecurityModule_GetEventsServer) error
	DumpProcessCache(context.Context, *DumpProcessCacheParams) (*SecurityDumpProcessCacheMessage, error)
	GetConfig(context.Context, *GetConfigParams) (*SecurityConfigMessage, error)
	GetStatus(context.Context, *GetStatusParams) (*Status, error)
	RunSelfTest(context.Context, *RunSelfTestParams) (*SecuritySelfTestResultMessage, error)
	ReloadPolicies(context.Context, *ReloadPoliciesParams) (*ReloadPoliciesResultMessage, error)
	DumpNetworkNamespace(context.Context, *DumpNetworkNamespaceParams) (*DumpNetworkNamespaceMessage, error)
	// Activity dumps
	DumpActivity(context.Context, *DumpActivityParams) (*SecurityActivityDumpMessage, error)
	ListActivityDumps(context.Context, *ListActivityDumpsParams) (*SecurityActivityDumpListMessage, error)
	StopActivityDump(context.Context, *StopActivityDumpParams) (*SecurityActivityDumpStoppedMessage, error)
	TranscodingRequest(context.Context, *TranscodingRequestParams) (*TranscodingRequestMessage, error)
}

// UnimplementedSecurityModuleServer can be embedded to have forward compatible implementations.
type UnimplementedSecurityModuleServer struct {
}

func (*UnimplementedSecurityModuleServer) GetEvents(req *GetEventParams, srv SecurityModule_GetEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (*UnimplementedSecurityModuleServer) DumpProcessCache(ctx context.Context, req *DumpProcessCacheParams) (*SecurityDumpProcessCacheMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpProcessCache not implemented")
}
func (*UnimplementedSecurityModuleServer) GetConfig(ctx context.Context, req *GetConfigParams) (*SecurityConfigMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (*UnimplementedSecurityModuleServer) GetStatus(ctx context.Context, req *GetStatusParams) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (*UnimplementedSecurityModuleServer) RunSelfTest(ctx context.Context, req *RunSelfTestParams) (*SecuritySelfTestResultMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSelfTest not implemented")
}
func (*UnimplementedSecurityModuleServer) ReloadPolicies(ctx context.Context, req *ReloadPoliciesParams) (*ReloadPoliciesResultMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadPolicies not implemented")
}
func (*UnimplementedSecurityModuleServer) DumpNetworkNamespace(ctx context.Context, req *DumpNetworkNamespaceParams) (*DumpNetworkNamespaceMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpNetworkNamespace not implemented")
}
func (*UnimplementedSecurityModuleServer) DumpActivity(ctx context.Context, req *DumpActivityParams) (*SecurityActivityDumpMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpActivity not implemented")
}
func (*UnimplementedSecurityModuleServer) ListActivityDumps(ctx context.Context, req *ListActivityDumpsParams) (*SecurityActivityDumpListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActivityDumps not implemented")
}
func (*UnimplementedSecurityModuleServer) StopActivityDump(ctx context.Context, req *StopActivityDumpParams) (*SecurityActivityDumpStoppedMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopActivityDump not implemented")
}
func (*UnimplementedSecurityModuleServer) TranscodingRequest(ctx context.Context, req *TranscodingRequestParams) (*TranscodingRequestMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TranscodingRequest not implemented")
}

func RegisterSecurityModuleServer(s *grpc.Server, srv SecurityModuleServer) {
	s.RegisterService(&_SecurityModule_serviceDesc, srv)
}

func _SecurityModule_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecurityModuleServer).GetEvents(m, &securityModuleGetEventsServer{stream})
}

type SecurityModule_GetEventsServer interface {
	Send(*SecurityEventMessage) error
	grpc.ServerStream
}

type securityModuleGetEventsServer struct {
	grpc.ServerStream
}

func (x *securityModuleGetEventsServer) Send(m *SecurityEventMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _SecurityModule_DumpProcessCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpProcessCacheParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).DumpProcessCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/DumpProcessCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).DumpProcessCache(ctx, req.(*DumpProcessCacheParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).GetConfig(ctx, req.(*GetConfigParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).GetStatus(ctx, req.(*GetStatusParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_RunSelfTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSelfTestParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).RunSelfTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/RunSelfTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).RunSelfTest(ctx, req.(*RunSelfTestParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_ReloadPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadPoliciesParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).ReloadPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/ReloadPolicies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).ReloadPolicies(ctx, req.(*ReloadPoliciesParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_DumpNetworkNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpNetworkNamespaceParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).DumpNetworkNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/DumpNetworkNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).DumpNetworkNamespace(ctx, req.(*DumpNetworkNamespaceParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_DumpActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpActivityParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).DumpActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/DumpActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).DumpActivity(ctx, req.(*DumpActivityParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_ListActivityDumps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivityDumpsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).ListActivityDumps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/ListActivityDumps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).ListActivityDumps(ctx, req.(*ListActivityDumpsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_StopActivityDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopActivityDumpParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).StopActivityDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/StopActivityDump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).StopActivityDump(ctx, req.(*StopActivityDumpParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_TranscodingRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscodingRequestParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).TranscodingRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/TranscodingRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).TranscodingRequest(ctx, req.(*TranscodingRequestParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecurityModule_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SecurityModule",
	HandlerType: (*SecurityModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DumpProcessCache",
			Handler:    _SecurityModule_DumpProcessCache_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _SecurityModule_GetConfig_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _SecurityModule_GetStatus_Handler,
		},
		{
			MethodName: "RunSelfTest",
			Handler:    _SecurityModule_RunSelfTest_Handler,
		},
		{
			MethodName: "ReloadPolicies",
			Handler:    _SecurityModule_ReloadPolicies_Handler,
		},
		{
			MethodName: "DumpNetworkNamespace",
			Handler:    _SecurityModule_DumpNetworkNamespace_Handler,
		},
		{
			MethodName: "DumpActivity",
			Handler:    _SecurityModule_DumpActivity_Handler,
		},
		{
			MethodName: "ListActivityDumps",
			Handler:    _SecurityModule_ListActivityDumps_Handler,
		},
		{
			MethodName: "StopActivityDump",
			Handler:    _SecurityModule_StopActivityDump_Handler,
		},
		{
			MethodName: "TranscodingRequest",
			Handler:    _SecurityModule_TranscodingRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _SecurityModule_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/security/api/api.proto",
}
